#!/usr/bin/env node
// Generate src/tables.g.ts from corpus/tables/*.json.
//
// The Python package is the source of every shared constant
// (python/pupiltree_latex/export_tables.py writes the JSON). This script is
// the only way the tables enter the JS package; never hand-edit the output.
//
//   node scripts/gen-tables.mjs [tables_dir]

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const tablesDir = resolve(
  process.argv[2] ?? join(here, "..", "..", "corpus", "tables"),
);
const outFile = join(here, "..", "src", "tables.g.ts");

function load(name) {
  const raw = readFileSync(join(tablesDir, `${name}.json`), "utf8");
  const doc = JSON.parse(raw);
  if (doc.name !== name)
    throw new Error(`${name}.json: name field is ${JSON.stringify(doc.name)}`);
  return doc;
}

// A string literal with every non-ASCII code unit written as \uXXXX, so the
// generated source is byte-stable in any editor (the mojibake table carries
// C1 control characters).
function lit(s) {
  if (typeof s !== "string")
    throw new TypeError(`expected a string, got ${typeof s}`);
  let out = '"';
  for (let i = 0; i < s.length; i++) {
    const c = s.charCodeAt(i);
    if (c === 0x22) out += '\\"';
    else if (c === 0x5c) out += "\\\\";
    else if (c >= 0x20 && c <= 0x7e) out += s[i];
    else out += "\\u" + c.toString(16).padStart(4, "0");
  }
  return out + '"';
}

function stringArray(values) {
  if (!Array.isArray(values)) throw new TypeError("expected an array");
  return "[\n" + values.map((v) => "  " + lit(v) + ",\n").join("") + "]";
}

function stringRecord(obj) {
  if (obj === null || typeof obj !== "object" || Array.isArray(obj))
    throw new TypeError("expected an object");
  return (
    "{\n" +
    Object.entries(obj)
      .map(([k, v]) => "  " + lit(k) + ": " + lit(v) + ",\n")
      .join("") +
    "}"
  );
}

function assertBmp(name, keys) {
  for (const k of keys) {
    for (const ch of k) {
      if (ch.length !== 1) {
        throw new Error(
          `${name}: key ${JSON.stringify(k)} has a non-BMP character; the per-code-unit walkers assume BMP keys`,
        );
      }
    }
  }
}

const names = {
  katex_commands: "set",
  non_katex_model_emissions: "set",
  json_whitespace_collision_commands: "set",
  latex_commands_behind_json_escapes: "set",
  audit_extra_allowed_commands: "set",
  non_content_keys: "set",
  not_rendered_keys: "set",
  script_labels: "set",
  symbol_commands: "set",
  collapse_commands: "array",
  structural_commands: "array",
  argument_commands: "array",
  unsupported_commands: "array",
  non_content_key_suffixes: "array",
  url_prefixes: "array",
  file_extensions: "array",
  unicode_math: "record",
  homoglyphs: "record",
  latex_cmd_map: "record",
  mojibake_table: "record",
  html_entities: "record",
  wrappable_bare_chars: "charset",
  joining_chars: "charset",
  joining_commands: "set",
  unit_bases: "set",
  single_letter_units: "charset",
  greek_math_letters: "charset",
  greek_unit_symbols: "array",
  declaration_commands: "array",
  html5_entities: "record",
  html_numeric_overrides: "record",
  compare_fold: "record",
  element_symbols: "set",
};

const docs = Object.fromEntries(Object.keys(names).map((n) => [n, load(n)]));
const versions = new Set(Object.values(docs).map((d) => d.version));
if (versions.size !== 1)
  throw new Error(`tables disagree on version: ${[...versions].join(", ")}`);
const [version] = versions;

assertBmp("unicode_math", Object.keys(docs.unicode_math.value));
assertBmp("homoglyphs", Object.keys(docs.homoglyphs.value));
assertBmp("mojibake_table", Object.keys(docs.mojibake_table.value));
assertBmp("wrappable_bare_chars", [...docs.wrappable_bare_chars.value]);
assertBmp("joining_chars", [...docs.joining_chars.value]);
assertBmp("greek_math_letters", [...docs.greek_math_letters.value]);
assertBmp("compare_fold", Object.keys(docs.compare_fold.value));

let src = "";
src +=
  "// GENERATED by scripts/gen-tables.mjs from corpus/tables/*.json — do not edit.\n";
src += "// Source of truth: python/pupiltree_latex (export_tables.py).\n\n";
src += `export const VERSION = ${lit(version)};\n\n`;

for (const [name, kind] of Object.entries(names)) {
  const constName = name.toUpperCase();
  const value = docs[name].value;
  if (kind === "set") {
    src += `export const ${constName}: ReadonlySet<string> = new Set<string>(${stringArray(value)});\n\n`;
  } else if (kind === "array") {
    src += `export const ${constName}: readonly string[] = ${stringArray(value)};\n\n`;
  } else if (kind === "record") {
    src += `export const ${constName}: Readonly<Record<string, string>> = ${stringRecord(value)};\n\n`;
  } else if (kind === "charset") {
    if (typeof value !== "string")
      throw new TypeError(`${name}: expected a string`);
    src += `export const ${constName}: ReadonlySet<string> = new Set<string>(${stringArray([...value])});\n\n`;
  }
}

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, src, "utf8");
console.log(
  `wrote ${outFile} (${Object.keys(names).length} tables, version ${version})`,
);
