/// Generate `lib/src/tables.g.dart` from `corpus/tables/*.json`.
///
///     dart run tool/gen_tables.dart
///
/// The Python package is the source of every table (`python -m
/// pupiltree_latex.export_tables`); this script embeds the JSON forms as Dart
/// constants so the two implementations cannot drift. Never edit the
/// generated file by hand.
library;

import 'dart:convert';
import 'dart:io';

/// JSON table name → Dart constant name.
const _names = <String, String>{
  'katex_commands': 'kKatexCommands',
  'non_katex_model_emissions': 'kNonKatexModelEmissions',
  'json_whitespace_collision_commands': 'kJsonWhitespaceCollisionCommands',
  'latex_commands_behind_json_escapes': 'kLatexCommandsBehindJsonEscapes',
  'collapse_commands': 'kCollapseCommands',
  'structural_commands': 'kStructuralCommands',
  'argument_commands': 'kArgumentCommands',
  'unsupported_commands': 'kUnsupportedCommands',
  'audit_extra_allowed_commands': 'kAuditExtraAllowedCommands',
  'unicode_math': 'kUnicodeMath',
  'homoglyphs': 'kHomoglyphs',
  'wrappable_bare_chars': 'kWrappableBareChars',
  'latex_cmd_map': 'kLatexCmdMap',
  'mojibake_table': 'kMojibakeTable',
  'non_content_keys': 'kNonContentKeys',
  'non_content_key_suffixes': 'kNonContentKeySuffixes',
  'not_rendered_keys': 'kNotRenderedKeys',
  'url_prefixes': 'kUrlPrefixes',
  'file_extensions': 'kFileExtensions',
  'script_labels': 'kScriptLabels',
  'symbol_commands': 'kSymbolCommands',
  'html_entities': 'kHtmlEntities',
  'joining_chars': 'kJoiningChars',
  'joining_commands': 'kJoiningCommands',
  'unit_bases': 'kUnitBases',
  'single_letter_units': 'kSingleLetterUnits',
  'greek_math_letters': 'kGreekMathLetters',
  'greek_unit_symbols': 'kGreekUnitSymbols',
  'declaration_commands': 'kDeclarationCommands',
  'html5_entities': 'kHtml5Entities',
  'html_numeric_overrides': 'kHtmlNumericOverrides',
  'compare_fold': 'kCompareFold',
  'element_symbols': 'kElementSymbols',
};

/// Tables whose JSON form is a list but whose Dart form is a `Set` (membership
/// lookups). The others stay ordered lists (regex alternations, suffix loops)
/// or maps (insertion order is load-bearing for `kMojibakeTable`).
const _sets = <String>{
  'katex_commands',
  'non_katex_model_emissions',
  'json_whitespace_collision_commands',
  'latex_commands_behind_json_escapes',
  'audit_extra_allowed_commands',
  'non_content_keys',
  'not_rendered_keys',
  'unsupported_commands',
  'script_labels',
  'symbol_commands',
  'joining_commands',
  'unit_bases',
  'element_symbols',
};

/// A Dart single-quoted string literal. Everything outside printable ASCII is
/// written as `\uXXXX` so the generated file is ASCII and every C1 control
/// character in the mojibake keys is visible.
String dartString(String s) {
  final b = StringBuffer("'");
  for (final unit in s.codeUnits) {
    if (unit == 0x27) {
      b.write(r"\'");
    } else if (unit == 0x5C) {
      b.write(r'\\');
    } else if (unit == 0x24) {
      b.write(r'\$');
    } else if (unit >= 0x20 && unit < 0x7F) {
      b.writeCharCode(unit);
    } else {
      b.write('\\u{${unit.toRadixString(16).padLeft(4, '0')}}');
    }
  }
  b.write("'");
  return b.toString();
}

String _render(String table, Object? value) {
  final name = _names[table]!;
  if (value is String) {
    // `wrappable_bare_chars` is one string of characters → a Set of chars.
    final chars = value.runes.map(String.fromCharCode).toList();
    return 'const Set<String> $name = {\n'
        '${chars.map((c) => '  ${dartString(c)},\n').join()}'
        '};\n';
  }
  if (value is List) {
    final items = value.cast<String>();
    final type = _sets.contains(table) ? 'Set<String>' : 'List<String>';
    final open = _sets.contains(table) ? '{' : '[';
    final close = _sets.contains(table) ? '}' : ']';
    return 'const $type $name = $open\n'
        '${items.map((c) => '  ${dartString(c)},\n').join()}'
        '$close;\n';
  }
  if (value is Map) {
    return 'const Map<String, String> $name = {\n'
        '${value.entries.map((e) => '  ${dartString(e.key as String)}: ${dartString(e.value as String)},\n').join()}'
        '};\n';
  }
  throw StateError('unexpected table shape for $table: ${value.runtimeType}');
}

void main(List<String> args) {
  final packageDir = File.fromUri(Platform.script).parent.parent;
  final tablesDir = args.isNotEmpty
      ? Directory(args[0])
      : Directory('${packageDir.path}/../../corpus/tables');
  final outFile = File('${packageDir.path}/lib/src/tables.g.dart');

  final out = StringBuffer()
    ..writeln('// GENERATED by tool/gen_tables.dart from corpus/tables/*.json.')
    ..writeln('// Do not edit by hand; run `dart run tool/gen_tables.dart`.')
    ..writeln('//')
    ..writeln('// ignore_for_file: lines_longer_than_80_chars')
    ..writeln();

  String? version;
  for (final table in _names.keys) {
    final file = File('${tablesDir.path}/$table.json');
    if (!file.existsSync()) {
      stderr.writeln('missing table: ${file.path}');
      exitCode = 1;
      return;
    }
    final doc = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
    final v = doc['version'] as String;
    if (version != null && version != v) {
      stderr
          .writeln('table version mismatch: $table has $v, expected $version');
      exitCode = 1;
      return;
    }
    version = v;
    out
      ..writeln('/// `corpus/tables/$table.json`.')
      ..write(_render(table, doc['value']))
      ..writeln();
  }
  out.writeln(
      '/// Version of the tables (and of the contract they belong to).');
  out.writeln('const String kVersion = ${dartString(version!)};');

  outFile.parent.createSync(recursive: true);
  outFile.writeAsStringSync(out.toString());
  stdout.writeln('wrote ${outFile.path} (version $version)');
}
