"""Curated corpus cases for `fix` (the one-call entry point).

Each row: (id, input, expected, tags, extra). Imported by build_corpus.py.
"""

FIX = [
    (
        "everything-at-once",
        "Cost $5 and \\(\\theta\\) with \x0crac{1}{2} and π and H₂O",
        "Cost \\$5 and $\\theta$ with $\\frac{1}{2}$ and $\\pi$ and $\\text{H}_{2}\\text{O}$",
        ["B1", "B3", "B4", "B6"],
        {},
    ),
    ("chem-water", "H₂O", "$\\text{H}_{2}\\text{O}$", ["B6"], {}),
    ("chem-baking-soda", "NaHCO₃", "$\\text{NaHCO}_{3}$", ["B6"], {}),
    ("chem-sulfate", "SO₄²⁻", "$\\text{SO}_{4}^{2-}$", ["B6"], {}),
    ("chem-iron-ion", "Fe³⁺", "$\\text{Fe}^{3+}$", ["B6"], {}),
    ("chem-parens", "Ca(OH)₂", "$\\text{Ca(OH)}_{2}$", ["B6"], {}),
    (
        "chem-prose-parens",
        "Water (H₂O) and CO₂.",
        "Water ($\\text{H}_{2}\\text{O}$) and $\\text{CO}_{2}$.",
        ["B6"],
        {},
    ),
    (
        "chem-coefficient",
        "2H₂ + O₂ → 2H₂O",
        "$\\text{2H}_{2}$ + $\\text{O}_{2} \\rightarrow \\text{2H}_{2}\\text{O}$",
        ["B6"],
        {},
    ),
    (
        "chem-inside-math-untouched",
        "$H₂O$ and H₂O",
        "$H_{2}O$ and $\\text{H}_{2}\\text{O}$",
        ["B6", "B7"],
        {},
    ),
    ("power-of-ten-is-a-script", "10⁸", "$10^{8}$", ["B6", "review-S6"], {}),
    (
        "lowercase-scripts-and-hydrate",
        "mc² and x₁ and xH₂O",
        "$mc^{2}$ and $x_{1}$ and $\\text{xH}_{2}\\text{O}$",
        ["B6", "review-S6"],
        {},
    ),
    ("plain-chem-text", "H2O is water", "H2O is water", ["B7"], {}),
    (
        "greek-and-symbols",
        "α + β ≤ π × 2",
        "$\\alpha$ + $\\beta \\leq \\pi \\times$ 2",
        ["B6"],
        {},
    ),
    ("mojibake-then-wrap", "Ï€ r^2", "$\\pi r^2$", ["B6"], {}),
    (
        "currency-and-formula",
        "Cost $60 and $x^2$ end",
        "Cost \\$60 and $x^2$ end",
        ["B3"],
        {},
    ),
    (
        "orphan-and-escape",
        "\\(\\theta\\) then \\nNext \\( orphan",
        "$\\theta$ then \nNext  orphan",
        ["B4", "B5"],
        {},
    ),
    (
        "identifiers-kept",
        "MCQ_SINGLE and q_001_easy and https://a/b_c.png and {{IMAGE:59_1}}",
        "MCQ_SINGLE and q_001_easy and https://a/b_c.png and {{IMAGE:59_1}}",
        ["B7"],
        {},
    ),
    (
        "control-chars",
        "3 \times 10^8 and \x0crac{a}{b}",
        "3 $\\times 10^8$ and $\\frac{a}{b}$",
        ["B1"],
        {},
    ),
    (
        "bare-symbol-command",
        "speed is 3 \\times 10^8 m/s",
        "speed is 3 $\\times 10^8$ m/s",
        ["B4"],
        {},
    ),
    (
        "bare-greek-command",
        "the angle \\theta is small",
        "the angle $\\theta$ is small",
        ["B4"],
        {},
    ),
    (
        "adjacent-spans-merged",
        "$\\alpha$ $\\beta$ and $x$  $y$",
        "$\\alpha \\beta$ and $x y$",
        ["B4"],
        {},
    ),
    ("display-spans-not-merged", "$$a$$ $$b$$", "$$a$$ $$b$$", ["B7"], {}),
    ("spans-with-prose-not-merged", "$a$ + $b$", "$a$ + $b$", ["B7"], {}),
    (
        "nested-frac-renders",
        "\\frac{\\frac{1}{2}}{3}",
        "$\\frac{\\frac{1}{2}}{3}$",
        ["B4"],
        {},
    ),
    (
        "sci-notation-unicode",
        "3 × 10⁸ m/s",
        "3 $\\times 10^{8}$ m/s",
        ["B6", "review-S6"],
        {},
    ),
    (
        "bare-sqrt-without-argument-left-alone",
        "use \\sqrt here",
        "use \\sqrt here",
        ["B7"],
        {},
    ),
    (
        "degree-and-units",
        "25 °C and 9.8 m/s²",
        "25 °C and 9.8 m/$\\text{s}^{2}$",
        ["B6", "audit2-units"],
        {},
    ),
    # A doubled backslash before a known command is JSON re-encoding damage
    # (Backend `_collapse_double_backslashes`), so it is collapsed and wrapped.
    (
        "double-escaped-command-collapsed-and-wrapped",
        "a \\\\times b",
        "a $\\times$ b",
        ["B1", "B4"],
        {},
    ),
    (
        "script-labels-untouched",
        "\\teacher: Hello class \\type: mcq \\read: page 4",
        "\\teacher: Hello class \\type: mcq \\read: page 4",
        ["B1", "real-data-D0"],
        {},
    ),
    (
        "broken-span-not-merged",
        "$\\bigcup$ $\\begin{pmatrix}$ $\\forall$",
        "$\\bigcup$ $\\begin{pmatrix}$ $\\forall$",
        ["B7", "real-data-D7"],
        {},
    ),
    (
        "grade-level-value-in-prose",
        "Grade 6_A section",
        "Grade 6_A section",
        ["B4"],
        {
            "note": "a class name (digits, underscore, capitals) is an identifier even in prose"
        },
    ),
    (
        "html-entity-and-symbol",
        "a &amp; b &times; c",
        "a & b $\\times$ c",
        ["B6", "real-data-D8"],
        {},
    ),
    ("underscore-before-chemistry", "TRUE_FALSE⁻", "TRUE_FALSE⁻", ["B7", "fuzz"], {}),
    (
        "image-marker-inside-url",
        "see gs://{{IMAGE:q2_fig}} -",
        "see gs://{{IMAGE:q2_fig}} -",
        ["B7", "fuzz"],
        {},
    ),
    (
        "hindi-prose-with-symbols",
        "यह α कण \\frac{1}{2} है",
        "यह $\\alpha$ कण $\\frac{1}{2}$ है",
        ["B6", "fuzz"],
        {},
    ),
    (
        "unicode-scripts-outside-math",
        "3 × 10⁻³ and mc² and x₁",
        "3 $\\times 10^{-3}$ and $mc^{2}$ and $x_{1}$",
        ["B6", "review-S6"],
        {},
    ),
    ("percent-in-math-escaped", "$50%$", "$50\\%$", ["B4", "review-F22"], {}),
    (
        "dollar-inside-text-escaped",
        "$\\text{costs $5}$",
        "$\\text{costs \\$5}$",
        ["B3", "review-F22"],
        {},
    ),
    ("adjacent-without-blank-merged", "$1$γ", "$1 \\gamma$", ["B4", "review-F5"], {}),
    (
        "text-group-unicode-kept-through-fix",
        "$\\text{H₂O}$",
        "$\\text{H₂O}$",
        ["B7", "review-F1"],
        {},
    ),
    (
        "greek-prose-linear",
        "α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω α β γ π ω",
        "$\\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega \\alpha \\beta \\gamma \\pi \\omega$",
        ["B6", "review-perf"],
        {},
    ),
    (
        "unit-after-number-upright",
        "240 cm³ and E = mc²",
        "240 $\\text{cm}^{3}$ and E = $mc^{2}$",
        ["B6", "final-C2"],
        {},
    ),
    (
        "matrix-survives-fix",
        "$\\begin{vmatrix}a&b\\\\c&d\\end{vmatrix}$",
        "$\\begin{vmatrix}a&b\\\\c&d\\end{vmatrix}$",
        ["B7", "final-R1"],
        {},
    ),
]
# ---------------------------------------------------------------------------
# Audit round 2 (2026-09-26): a new span never ends right before a digit, a
# Unicode script or a literal `$`; symbols take their tight operands with them.
# ---------------------------------------------------------------------------

FIX += [
    (
        "audit2-times-chain",
        "The product 3×4×5=60 is easy.",
        "The product $3\\times4\\times5$=60 is easy.",
        ["B6", "audit2-cluster"],
        {},
    ),
    (
        "audit2-relations-with-digits",
        "If x≤5 then y≥2.",
        "If $x\\leq5$ then $y\\geq2$.",
        ["B6", "audit2-cluster"],
        {},
    ),
    (
        "audit2-sci-notation-in-prose",
        "Find 3.14×10⁻⁵ in standard form.",
        "Find $3.14\\times10^{-5}$ in standard form.",
        ["B6", "audit2-cluster"],
        {},
    ),
    (
        "audit2-sci-notation-alone",
        "3.14×10⁻⁵",
        "$3.14\\times10^{-5}$",
        ["B6", "audit2-cluster"],
        {},
    ),
    (
        "audit2-sci-notation-with-math",
        "3×10⁸ m/s and $E=mc^2$",
        "$3\\times10^{8}$ m/s and $E=mc^2$",
        ["B6", "audit2-cluster"],
        {},
    ),
    (
        "audit2-avogadro-tight",
        "6.022×10²³ particles",
        "$6.022\\times10^{23}$ particles",
        ["B6", "audit2-cluster", "audit2-script-not-word"],
        {},
    ),
    (
        "audit2-avogadro-alone",
        "6.022×10²³",
        "$6.022\\times10^{23}$",
        ["B6", "audit2-script-not-word"],
        {},
    ),
    (
        "audit2-hydrate",
        "CuSO₄·5H₂O",
        "$\\text{CuSO}_{4} \\cdot5 \\text{H}_{2}\\text{O}$",
        ["B6", "audit2-cluster"],
        {},
    ),
    (
        "audit2-arrows-with-operands",
        "Take n→∞ and x→0.",
        "Take $n\\rightarrow\\infty$ and $x\\rightarrow0$.",
        ["B6", "audit2-cluster"],
        {},
    ),
    (
        "audit2-greek-subscript",
        "Given ε₀ and μ₀, find c.",
        "Given $\\epsilon_{0}$ and $\\mu_{0}$, find c.",
        ["B6", "audit2-cluster"],
        {},
    ),
    (
        "audit2-greek-subscript-list",
        "λ₁, λ₂ are eigenvalues.",
        "$\\lambda_{1}$, $\\lambda_{2}$ are eigenvalues.",
        ["B6", "audit2-cluster"],
        {},
    ),
    (
        "audit2-greek-two-digit-subscript",
        "σ₁₂",
        "$\\sigma_{12}$",
        ["B6", "audit2-cluster"],
        {},
    ),
    (
        "audit2-micro-sign-subscript",
        "µ₀ = 4π × 10⁻⁷ T·m/A",
        "$\\mu_{0}$ = $4\\pi \\times 10^{-7}$ T$\\cdot$m/A",
        ["B6", "audit2-cluster", "audit3-greek-word"],
        {},
    ),
    (
        "audit2-operands-both-sides",
        "a×b and x→y",
        "$a\\times b$ and $x\\rightarrow y$",
        ["B6", "audit2-cluster"],
        {},
    ),
    (
        "audit2-script-then-relation",
        "x²≤5",
        "$x^{2}\\leq5$",
        ["B6", "audit2-cluster"],
        {},
    ),
    (
        "audit2-bare-command-before-digit",
        "x\\leq5 holds",
        "$x\\leq5$ holds",
        ["B4", "audit2-cluster"],
        {},
    ),
    (
        "audit2-stray-dollars-before-digit",
        "x$\\leq$5 holds",
        "$x\\leq5$ holds",
        ["B4", "audit2-cluster"],
        {},
    ),
    (
        "audit2-bare-pi-before-digit",
        "Use \\pi2 here",
        "Use $\\pi2$ here",
        ["B4", "audit2-cluster"],
        {},
    ),
    (
        "audit2-mixed-times",
        "2×10 and 3 \\times4",
        "$2\\times10$ and 3 $\\times4$",
        ["B4", "B6", "audit2-cluster"],
        {},
    ),
    (
        "audit2-command-with-scripts",
        "\\alpha_1 and \\beta^2",
        "$\\alpha_1$ and $\\beta^2$",
        ["B4", "audit2-cluster"],
        {},
    ),
    (
        "audit2-units-next-to-greek-stay-out",
        "µs and kΩ and J·s",
        "$\\mu$s and k$\\Omega$ and J$\\cdot$s",
        ["B6", "B7", "audit2-cluster"],
        {},
    ),
    (
        "audit2-lone-dollar-before-symbol",
        "$×5",
        "$ $\\times5$",
        ["B4", "audit2-lone-dollar"],
        {},
    ),
    (
        "audit2-line-break-then-frac",
        "\\\\\\frac{1}{2}",
        "\\\\$\\frac{1}{2}$",
        ["B4", "audit2-line-break-dollar"],
        {},
    ),
    (
        "audit2-lone-dollar-then-chemistry",
        "$ H₂",
        "$ $\\text{H}_{2}$",
        ["B4", "B6", "audit2-lone-dollar"],
        {},
    ),
    (
        "audit2-padded-span-trimmed",
        "Solve $ x^2 + 1 = 0 $ now",
        "Solve $x^2 + 1 = 0$ now",
        ["B4", "audit2-padded-span"],
        {},
    ),
    (
        "audit2-padded-span-with-command",
        "Let $ \\theta = 30° $ here",
        "Let $\\theta = 30^{\\circ}$ here",
        ["B4", "audit2-padded-span"],
        {},
    ),
    (
        "audit2-unit-after-slash",
        "m/s²",
        "m/$\\text{s}^{2}$",
        ["B6", "audit2-units"],
        {},
    ),
    (
        "audit2-unit-mol",
        "6.022 × 10²³ mol⁻¹",
        "6.022 $\\times 10^{23} \\text{mol}^{-1}$",
        ["B6", "audit2-units"],
        {},
    ),
    (
        "audit2-unit-per-mm",
        "per mm³",
        "per $\\text{mm}^{3}$",
        ["B6", "audit2-units"],
        {},
    ),
    (
        "audit2-unit-slash-and-number",
        "N/m² and 5 m² and 3 km²",
        "N/$\\text{m}^{2}$ and 5 $\\text{m}^{2}$ and 3 $\\text{km}^{2}$",
        ["B6", "audit2-units"],
        {},
    ),
    (
        "audit2-variables-stay-italic",
        "x² and a² and a/b²",
        "$x^{2}$ and $a^{2}$ and a/$b^{2}$",
        ["B6", "B7", "audit2-units"],
        {},
    ),
    ("audit2-mojibake-euro", "â‚¬5", "€5", ["B6", "audit2-currency-mojibake"], {}),
    (
        "audit2-mojibake-rupee",
        "â‚¹2,50,000 and Â£5",
        "₹2,50,000 and £5",
        ["B6", "audit2-currency-mojibake"],
        {},
    ),
    ("audit2-double-pi", "ππ", "$\\pi\\pi$", ["B6", "audit2-double-greek"], {}),
    (
        "audit2-mojibake-double-pi",
        "Ï€Ï€",
        "$\\pi\\pi$",
        ["B6", "audit2-double-greek"],
        {},
    ),
    # Audit round 3: Greek words and unclosed groups.
    (
        "audit3-greek-word-circle",
        "Area = 2πr and πr²",
        "Area = $2\\pi r$ and $\\pi r^{2}$",
        ["B6", "audit3-greek-word"],
        {},
    ),
    (
        "audit3-greek-word-uncertainty",
        "Δx·Δp ≥ ħ/2",
        "$\\Delta x\\cdot\\Delta p \\geq \\hbar$/2",
        ["B6", "audit3-greek-word"],
        {},
    ),
    (
        "audit3-greek-word-chemistry-left-to-chemistry",
        "ΔH₂O",
        "$\\Delta \\text{H}_{2}\\text{O}$",
        ["B6", "audit3-greek-word"],
        {},
    ),
    (
        "audit3-greek-word-with-ascii-script",
        "πr^2 and 2πr_1",
        "$\\pi r^2$ and $2\\pi r_1$",
        ["B6", "audit3-greek-word"],
        {},
    ),
    (
        "audit3-greek-word-after-joining-operator",
        "x≤2πr and 3×πr",
        "$x\\leq2\\pi r$ and $3\\times\\pi r$",
        ["B6", "audit3-greek-word"],
        {},
    ),
    (
        "audit3-greek-word-units-kept",
        "5 µs, 10 kΩ, 3 MΩ, 2 µm, 5 µg, 4 mΩ, Ω·m, J·s",
        "5 $\\mu$s, 10 k$\\Omega$, 3 M$\\Omega$, 2 $\\mu$m, 5 $\\mu$g, 4 m$\\Omega$, $\\Omega\\cdot$m, J$\\cdot$s",
        ["B6", "B7", "audit3-greek-word"],
        {},
    ),
    (
        "audit3-greek-word-radical-coefficient-kept",
        "2√3",
        "2$\\sqrt{3}$",
        ["B7", "audit3-greek-word"],
        {"note": "√ is not a Greek letter: Backend #1654 shape"},
    ),
    (
        "audit3-brace-close-frac",
        "a $\\frac{1}{2$ b",
        "a $\\frac{1}{2}$ b",
        ["B4", "audit3-brace-close"],
        {},
    ),
    (
        "audit3-brace-close-then-closed-span",
        "$\\sqrt{x+1$ and $y$",
        "$\\sqrt{x+1}$ and $y$",
        ["B4", "audit3-brace-close"],
        {},
    ),
    (
        "audit3-script-group-euler",
        "e^{iπ}",
        "$e^{i\\pi}$",
        ["B5", "B6", "audit3-script-group"],
        {},
    ),
    (
        "audit3-script-group-symbol-after-script",
        "10^{-3}μ and sin^{2}θ",
        "$10^{-3} \\mu$ and $sin^{2} \\theta$",
        ["B6", "audit3-script-group"],
        {},
    ),
    (
        "audit3-script-group-command-arguments",
        "use \\frac{π}{2} here and e^{iθ}",
        "use $\\frac{\\pi}{2}$ here and $e^{i\\theta}$",
        ["B5", "B6", "audit3-script-group"],
        {},
    ),
]


# Audit round 4 (2026-10-08, v1.2.0). See build_corpus.py for the other
# functions' `audit4-<n>` cases.
FIX += [
    # audit4-1
    ("audit4-1-gap-title", "Gap: lo_0", "Gap: lo_0", ["B7", "audit4-1"], {}),
    (
        "audit4-1-script-still-wraps",
        "Gap: lo_0 and x_0",
        "Gap: lo_0 and $x_0$",
        ["B5", "B7", "audit4-1"],
        {},
    ),
    # audit4-6
    (
        "audit4-6-space-before-closer",
        "Compute $2x + 3 $.",
        "Compute $2x + 3$.",
        ["B3", "audit4-6"],
        {},
    ),
    (
        "audit4-6-prices-still-currency",
        "Prices: $10, $20 and $5 and $10",
        "Prices: \\$10, \\$20 and \\$5 and \\$10",
        ["B3", "audit4-6"],
        {},
    ),
    # audit4-8
    (
        "audit4-8-ce-wrapped-by-default",
        "\\ce{H2O}",
        "$\\ce{H2O}$",
        ["B6", "audit4-8"],
        {},
    ),
    (
        "audit4-8-ce-left-bare-without-chemistry",
        "\\ce{H2O}",
        "\\ce{H2O}",
        ["B6", "B7", "audit4-8"],
        {"opts": {"chemistry": False}},
    ),
    (
        "audit4-8-pu-left-bare-without-chemistry",
        "\\pu{5 kg}",
        "\\pu{5 kg}",
        ["B6", "B7", "audit4-8"],
        {"opts": {"chemistry": False}},
    ),
    (
        "audit4-8-other-math-still-wrapped-without-chemistry",
        "\\ce{H2O} has H₂O and x≤5",
        "\\ce{H2O} has $\\text{H}_{2}\\text{O}$ and $x\\leq5$",
        ["B6", "audit4-8"],
        {"opts": {"chemistry": False}},
    ),
    (
        "audit4-8-pure-math-without-chemistry",
        "\\frac{1}{2} + \\alpha",
        "$\\frac{1}{2} + \\alpha$",
        ["B6", "audit4-8"],
        {"opts": {"chemistry": False}},
    ),
    # audit4-9
    (
        "audit4-9-declaration-not-merged",
        "$\\forall$ $\\flat$ $\\bf x$",
        "$\\forall \\flat$ $\\bf x$",
        ["B7", "audit4-9"],
        {},
    ),
    (
        "audit4-9-colour-and-size-not-merged",
        "$\\color{red} a$ $b$ and $c$ $\\Large d$ $e$",
        "$\\color{red} a$ $b$ and $c$ $\\Large d$ $e$",
        ["B7", "audit4-9"],
        {},
    ),
    (
        "audit4-9-boldsymbol-still-merges",
        "$\\boldsymbol{x}$ $\\times$ $y$",
        "$\\boldsymbol{x} \\times y$",
        ["B7", "audit4-9"],
        {},
    ),
    # audit5-8: fix is idempotent on `$ $` shapes; `\nu` is never decoded to
    # a newline + "u" (the corpus checks fix(fix(x)) == fix(x) too).
    (
        "audit5-8-malformed-idempotent",
        "$\\nu = $\\frac{c}{\\lambd$a^{{2}$}$}$",
        "$ $\\nu$ = $\\frac{c}{\\lambd$a^{{2}$}$}$",
        ["B5", "B7", "audit5-8"],
        {},
    ),
    (
        "audit5-8-empty-padded-pair-keeps-nu",
        "a $ $\\nu$ b",
        "a $ $\\nu$ b",
        ["B5", "audit5-8"],
        {},
    ),
    (
        "audit5-8-two-empty-padded-pairs",
        "x $ $\\ne$ y $ $\\theta$",
        "x $ $\\ne$ y $ $\\theta$",
        ["B5", "audit5-8"],
        {},
    ),
    (
        "audit5-8-padded-span-keeps-ne",
        "$ x \\ne y $",
        "$x \\ne y$",
        ["B5", "audit5-8"],
        {},
    ),
]
